# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0002_auto_20180712_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='related_snippet',
            field=models.ManyToManyField(related_name='snippets', to='personal_site.Snippet'),
        ),
    ]
