# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0004_auto_20180713_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
    ]
