# Generated by Django 3.0.5 on 2020-05-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0005_auto_20180713_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='related_snippet',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
